version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: reciclaje_dev_db
    restart: always
    environment:
      POSTGRES_DB: reciclaje_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Bogota
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reciclaje_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reciclaje_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  reciclaje_network:
    driver: bridge