"""Add purchase and inventory_movement models

Revision ID: 5e2476c73ba1
Revises: 0f370810944e
Create Date: 2026-02-01 15:31:52.816099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5e2476c73ba1'
down_revision: Union[str, Sequence[str], None] = '0f370810944e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_number', sa.Integer(), nullable=False, comment='Sequential number per organization (1, 2, 3...)'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Supplier (must have is_supplier=True)'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False, comment='Purchase date (weighing date, not payment date)'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total purchase amount (sum of all line totals)'),
    sa.Column('status', sa.Enum('registered', 'paid', 'cancelled', name='purchase_status'), nullable=False, comment='registered=pending payment, paid=completed, cancelled=voided'),
    sa.Column('payment_account_id', sa.UUID(), nullable=True, comment="Account used for payment (required when status='paid')"),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or observations'),
    sa.Column('organization_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_account_id'], ['money_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['third_parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'purchase_number', name='uq_purchase_number_per_org')
    )
    op.create_index(op.f('ix_purchases_date'), 'purchases', ['date'], unique=False)
    op.create_index('ix_purchases_org_date', 'purchases', ['organization_id', 'date'], unique=False)
    op.create_index('ix_purchases_org_status', 'purchases', ['organization_id', 'status'], unique=False)
    op.create_index('ix_purchases_org_supplier', 'purchases', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_purchases_organization_id'), 'purchases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchases_payment_account_id'), 'purchases', ['payment_account_id'], unique=False)
    op.create_index(op.f('ix_purchases_purchase_number'), 'purchases', ['purchase_number'], unique=False)
    op.create_index(op.f('ix_purchases_status'), 'purchases', ['status'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False, comment='Material being moved'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Warehouse where movement occurred'),
    sa.Column('movement_type', sa.Enum('purchase', 'sale', 'adjustment', 'transfer', 'purchase_reversal', 'sale_reversal', 'transformation', name='inventory_movement_type'), nullable=False, comment='Type of inventory movement'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Quantity moved (positive=in, negative=out)'),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False, comment='Cost per unit at time of movement'),
    sa.Column('reference_type', sa.Enum('purchase', 'sale', 'adjustment', 'transfer', 'transformation', name='inventory_reference_type'), nullable=True, comment='Type of referenced transaction'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='ID of referenced transaction (NULL for manual adjustments)'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False, comment='Date of movement'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or reason for movement'),
    sa.Column('organization_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_date'), 'inventory_movements', ['date'], unique=False)
    op.create_index(op.f('ix_inventory_movements_material_id'), 'inventory_movements', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index('ix_inventory_movements_org_date', 'inventory_movements', ['organization_id', 'date'], unique=False)
    op.create_index('ix_inventory_movements_org_material', 'inventory_movements', ['organization_id', 'material_id'], unique=False)
    op.create_index('ix_inventory_movements_org_type', 'inventory_movements', ['organization_id', 'movement_type'], unique=False)
    op.create_index('ix_inventory_movements_org_warehouse', 'inventory_movements', ['organization_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_organization_id'), 'inventory_movements', ['organization_id'], unique=False)
    op.create_index('ix_inventory_movements_reference', 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_id'), 'inventory_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_warehouse_id'), 'inventory_movements', ['warehouse_id'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Quantity purchased (allows decimals: 150.500 kg)'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Price per unit'),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Line total (quantity × unit_price)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_lines_material', 'purchase_lines', ['material_id'], unique=False)
    op.create_index(op.f('ix_purchase_lines_material_id'), 'purchase_lines', ['material_id'], unique=False)
    op.create_index('ix_purchase_lines_purchase', 'purchase_lines', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_purchase_lines_purchase_id'), 'purchase_lines', ['purchase_id'], unique=False)
    op.create_index('ix_purchase_lines_warehouse', 'purchase_lines', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_purchase_lines_warehouse_id'), 'purchase_lines', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'business_units', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('material_categories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'material_categories', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'materials', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'money_accounts', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'third_parties', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'warehouses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_constraint(None, 'third_parties', type_='foreignkey')
    op.drop_constraint(None, 'money_accounts', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'material_categories', type_='foreignkey')
    op.drop_column('material_categories', 'is_active')
    op.drop_constraint(None, 'business_units', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_lines_warehouse_id'), table_name='purchase_lines')
    op.drop_index('ix_purchase_lines_warehouse', table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_purchase_id'), table_name='purchase_lines')
    op.drop_index('ix_purchase_lines_purchase', table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_material_id'), table_name='purchase_lines')
    op.drop_index('ix_purchase_lines_material', table_name='purchase_lines')
    op.drop_table('purchase_lines')
    op.drop_index(op.f('ix_inventory_movements_warehouse_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_id'), table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_reference', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_organization_id'), table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_org_warehouse', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_org_type', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_org_material', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_org_date', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_material_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_date'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_status'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchase_number'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_payment_account_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_organization_id'), table_name='purchases')
    op.drop_index('ix_purchases_org_supplier', table_name='purchases')
    op.drop_index('ix_purchases_org_status', table_name='purchases')
    op.drop_index('ix_purchases_org_date', table_name='purchases')
    op.drop_index(op.f('ix_purchases_date'), table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
