"""add_sale_tables

Revision ID: 8fccbad5f3f6
Revises: 5e2476c73ba1
Create Date: 2026-02-01 19:14:55.425489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fccbad5f3f6'
down_revision: Union[str, Sequence[str], None] = '5e2476c73ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_number', sa.Integer(), nullable=False, comment='Sequential sale number within organization (1, 2, 3...)'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Customer (ThirdParty with is_customer=True)'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Source warehouse for all sale lines'),
    sa.Column('payment_account_id', sa.UUID(), nullable=True, comment="Payment account (set when status='paid')"),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False, comment='Sale date'),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True, comment='Vehicle plate number for delivery/pickup'),
    sa.Column('invoice_number', sa.String(length=50), nullable=True, comment='Invoice or bill number'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total sale amount (sum of all lines)'),
    sa.Column('status', sa.Enum('registered', 'paid', 'cancelled', name='sale_status'), nullable=False, comment='Sale status: registered (pending payment) | paid | cancelled'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or observations'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['third_parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_account_id'], ['money_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sale_number', name='uq_sales_org_number')
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index('ix_sales_date_status', 'sales', ['date', 'status'], unique=False)
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=False)
    op.create_index('ix_sales_org_customer', 'sales', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_sales_org_date', 'sales', ['organization_id', 'date'], unique=False)
    op.create_index('ix_sales_org_status', 'sales', ['organization_id', 'status'], unique=False)
    op.create_index('ix_sales_org_warehouse', 'sales', ['organization_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sales_payment_account_id'), 'sales', ['payment_account_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_number'), 'sales', ['sale_number'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_index(op.f('ix_sales_warehouse_id'), 'sales', ['warehouse_id'], unique=False)
    op.create_table('sale_commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('third_party_id', sa.UUID(), nullable=False, comment='Person/entity receiving the commission'),
    sa.Column('commission_type', sa.Enum('percentage', 'fixed', name='commission_type'), nullable=False, comment='percentage (of sale total) or fixed amount'),
    sa.Column('commission_value', sa.Numeric(precision=15, scale=2), nullable=False, comment='Percentage (0-100) or fixed amount'),
    sa.Column('commission_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Calculated commission amount'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['third_party_id'], ['third_parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_commissions_sale_id'), 'sale_commissions', ['sale_id'], unique=False)
    op.create_index('ix_sale_commissions_third_party_id', 'sale_commissions', ['third_party_id'], unique=False)
    op.create_table('sale_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Quantity sold (must be positive)'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Selling price per unit'),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total line price (quantity × unit_price)'),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False, comment='Average cost at moment of sale (for profit calculation)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_lines_material_id', 'sale_lines', ['material_id'], unique=False)
    op.create_index(op.f('ix_sale_lines_sale_id'), 'sale_lines', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_lines_sale_id'), table_name='sale_lines')
    op.drop_index('ix_sale_lines_material_id', table_name='sale_lines')
    op.drop_table('sale_lines')
    op.drop_index('ix_sale_commissions_third_party_id', table_name='sale_commissions')
    op.drop_index(op.f('ix_sale_commissions_sale_id'), table_name='sale_commissions')
    op.drop_table('sale_commissions')
    op.drop_index(op.f('ix_sales_warehouse_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_payment_account_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_index('ix_sales_org_warehouse', table_name='sales')
    op.drop_index('ix_sales_org_status', table_name='sales')
    op.drop_index('ix_sales_org_date', table_name='sales')
    op.drop_index('ix_sales_org_customer', table_name='sales')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_index('ix_sales_date_status', table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
