"""add_concept_field_to_sale_commission

Revision ID: ae8259752a81
Revises: 8fccbad5f3f6
Create Date: 2026-02-01 19:30:36.730154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8259752a81'
down_revision: Union[str, Sequence[str], None] = '8fccbad5f3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_commissions', sa.Column('concept', sa.String(length=255), nullable=False, comment="Commission description (e.g., 'Comisión facturación', 'Intermediario')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_commissions', 'concept')
    # ### end Alembic commands ###
