"""add_audit_fields_to_purchases_and_sales

Revision ID: beb1e434a605
Revises: 3686aa004516
Create Date: 2026-02-14 12:34:00.699001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb1e434a605'
down_revision: Union[str, Sequence[str], None] = '3686aa004516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('vehicle_plate', sa.String(length=20), nullable=True, comment='Vehicle plate number for delivery'))
    op.add_column('purchases', sa.Column('invoice_number', sa.String(length=50), nullable=True, comment='Invoice or bill number'))
    op.add_column('purchases', sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the purchase (weighing operator)'))
    op.add_column('purchases', sa.Column('liquidated_by', sa.UUID(), nullable=True, comment='User who liquidated/paid the purchase'))
    op.create_index(op.f('ix_purchases_invoice_number'), 'purchases', ['invoice_number'], unique=False)
    op.create_foreign_key(None, 'purchases', 'users', ['liquidated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'purchases', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('sales', sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the sale'))
    op.add_column('sales', sa.Column('liquidated_by', sa.UUID(), nullable=True, comment='User who liquidated/collected the sale'))
    op.alter_column('sales', 'warehouse_id',
               existing_type=sa.UUID(),
               comment='Source warehouse for sale lines. NULL for double-entry operations.',
               existing_comment='Source warehouse for all sale lines',
               existing_nullable=True)
    op.create_foreign_key(None, 'sales', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sales', 'users', ['liquidated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.alter_column('sales', 'warehouse_id',
               existing_type=sa.UUID(),
               comment='Source warehouse for all sale lines',
               existing_comment='Source warehouse for sale lines. NULL for double-entry operations.',
               existing_nullable=True)
    op.drop_column('sales', 'liquidated_by')
    op.drop_column('sales', 'created_by')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_invoice_number'), table_name='purchases')
    op.drop_column('purchases', 'liquidated_by')
    op.drop_column('purchases', 'created_by')
    op.drop_column('purchases', 'invoice_number')
    op.drop_column('purchases', 'vehicle_plate')
    # ### end Alembic commands ###
