"""add_double_entry_model_and_links

Revision ID: f8ef89451aa6
Revises: ae8259752a81
Create Date: 2026-02-01 20:14:30.854513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ef89451aa6'
down_revision: Union[str, Sequence[str], None] = 'ae8259752a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('double_entry_number', sa.Integer(), nullable=False, comment='Sequential number per organization'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date of the double-entry operation'),
    sa.Column('material_id', sa.UUID(), nullable=False, comment='Material being traded'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Quantity of material (must be positive)'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Supplier from whom we purchase'),
    sa.Column('purchase_unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Purchase price per unit'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Customer to whom we sell'),
    sa.Column('sale_unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Sale price per unit'),
    sa.Column('invoice_number', sa.String(length=50), nullable=True, comment='Invoice number (optional)'),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True, comment='Vehicle plate for transport (optional)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('purchase_id', sa.UUID(), nullable=False, comment='Linked purchase record'),
    sa.Column('sale_id', sa.UUID(), nullable=False, comment='Linked sale record'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Status: 'completed' or 'cancelled'"),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['third_parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['third_parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id'),
    sa.UniqueConstraint('sale_id')
    )
    op.create_index(op.f('ix_double_entries_customer_id'), 'double_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_double_entries_date'), 'double_entries', ['date'], unique=False)
    op.create_index('ix_double_entries_date_status', 'double_entries', ['date', 'status'], unique=False)
    op.create_index(op.f('ix_double_entries_material_id'), 'double_entries', ['material_id'], unique=False)
    op.create_index('ix_double_entries_org_customer', 'double_entries', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_double_entries_org_date', 'double_entries', ['organization_id', 'date'], unique=False)
    op.create_index('ix_double_entries_org_material', 'double_entries', ['organization_id', 'material_id'], unique=False)
    op.create_index('ix_double_entries_org_status', 'double_entries', ['organization_id', 'status'], unique=False)
    op.create_index('ix_double_entries_org_supplier', 'double_entries', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_double_entries_organization_id'), 'double_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_double_entries_status'), 'double_entries', ['status'], unique=False)
    op.create_index(op.f('ix_double_entries_supplier_id'), 'double_entries', ['supplier_id'], unique=False)
    op.alter_column('purchase_lines', 'warehouse_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Warehouse (nullable for double-entry operations)')
    op.add_column('purchases', sa.Column('double_entry_id', sa.UUID(), nullable=True, comment='Link to double-entry operation if applicable'))
    op.create_foreign_key(None, 'purchases', 'double_entries', ['double_entry_id'], ['id'], ondelete='SET NULL')
    op.add_column('sales', sa.Column('double_entry_id', sa.UUID(), nullable=True, comment='Link to double-entry operation if applicable'))
    op.create_foreign_key(None, 'sales', 'double_entries', ['double_entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'double_entry_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'double_entry_id')
    op.alter_column('purchase_lines', 'warehouse_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='Warehouse (nullable for double-entry operations)')
    op.drop_index(op.f('ix_double_entries_supplier_id'), table_name='double_entries')
    op.drop_index(op.f('ix_double_entries_status'), table_name='double_entries')
    op.drop_index(op.f('ix_double_entries_organization_id'), table_name='double_entries')
    op.drop_index('ix_double_entries_org_supplier', table_name='double_entries')
    op.drop_index('ix_double_entries_org_status', table_name='double_entries')
    op.drop_index('ix_double_entries_org_material', table_name='double_entries')
    op.drop_index('ix_double_entries_org_date', table_name='double_entries')
    op.drop_index('ix_double_entries_org_customer', table_name='double_entries')
    op.drop_index(op.f('ix_double_entries_material_id'), table_name='double_entries')
    op.drop_index('ix_double_entries_date_status', table_name='double_entries')
    op.drop_index(op.f('ix_double_entries_date'), table_name='double_entries')
    op.drop_index(op.f('ix_double_entries_customer_id'), table_name='double_entries')
    op.drop_table('double_entries')
    # ### end Alembic commands ###
